name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: windows-latest
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          aria2c https://github.com/mstorsjo/llvm-mingw/releases/download/20251216/llvm-mingw-20251216-ucrt-x86_64.zip
          choco install 7zip
          7z x llvm-mingw-20251216-ucrt-x86_64.zip

      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch
        with:
          vcpkgGitCommitId: '84bab45d415d22042bd0b9081aea57f362da3f35'
          
      - name: Install libraries from vcpkg
        run: |
          $env:path += ";${{ env.llvm_path }}/bin"
          cd ${{ env.RUNVCPKG_VCPKG_ROOT }}
          # clear buildtrees after each package installation to reduce disk space requirements
          mkdir triplets_overlay
          cp triplets/community/x64-mingw-dynamic.cmake triplets_overlay/x64-mingw-dynamic-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/x64-mingw-dynamic-release.cmake
          $packages = `
            "openblas[threads]:x64-mingw-dynamic-release",
            "lapack:x64-mingw-dynamic-release",
            "fftw3[threads]:x64-mingw-dynamic-release"
          ./vcpkg upgrade `
            --no-dry-run
          ./vcpkg install `
            --clean-after-build `
            --overlay-triplets=triplets_overlay `
            $packages
          ./vcpkg export $packages --zip --output=packages

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages.zip